themoviedb:
    apiKey: 72b56103e43843412a992a8d64bf96e9
    accessUri: https://api.themoviedb.org/3
    pageLimit: 30

movie:
    requestRate: 10

---
spring:
    profiles: test
themoviedb:
    pageLimit: 100